---
train:
  params:
    batch_size: 80
    epoch: 100
    lr: 0.00001
    patience: 10 
    cooldown: 0
    min_lr: 0 
    decay: 
    decay_step: 
    loss: 
  save:
    save_path: "save"
    model_name: 
    step: 10
  data:
    image: "data/MPIIFaceGaze/Image"
    label: "data/MPIIFaceGazec/Label"
  pretrains: "None"
test:
   load:
      begin_step: 20
      end_step: 20
      steps: 1
      load_path: "save"
      model_name: None
   data:
      image: "data/MPIIFaceGazec/Image"
      label: "data/MPIIFaceGazec/Label"
reader: reader_mpii
